version: '3.9'
services:
  dev-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: sharenergy
    ports:
      - 27017:27017
    networks:
      - myNetwork
  test-db:
    image: mongo:latest
    environment:
      MONGO_INITDB_DATABASE: sharenergy
    ports:
      - 27018:27017
    networks:
      - myNetwork
networks:
  myNetwork: